//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenditure
    {
        public int ExpenditureID { get; set; }
        public string EName { get; set; }
        public string EPrice { get; set; }
        public Nullable<int> JourneyID { get; set; }
    
        public virtual Journey Journey { get; set; }
    }
}
