//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeSplit.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int MemberID { get; set; }
        public string MName { get; set; }
        public string MDonation { get; set; }
        public string MAvatar { get; set; }
        public Nullable<int> JourneyID { get; set; }
    
        public virtual Journey Journey { get; set; }
    }
}
